version: '3'
services:
  ss-chat:
    build: .
    ports:
      - "1337:1337"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
    volumes:
      - app-data:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  app-data:
  mongo-data: