version: '3'
services:
  ss-chat:
    build: .
    ports:
      - "1337:1337"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - JWT_SECRET=c5e3e7636d890364934ec989490707419b32a6a6be74ca99cc1803b5315a8825
    volumes:
      - app-data:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  app-data:
  mongo-data: